# Node.js with Angular

# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'npm install and build'
  
- script: |
    ng build --configuration=production
  displayName: 'npm run build'

- script: node -v
  displayName: 'Display Node.js version'

- script: ls
  displayName: 'List contents of working directory'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'dist'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/dist'
  displayName: 'Copy files to artifact staging directory'


- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: true
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '**/*.zip'
    destinationFolder: '$(Build.ArtifactStagingDirectory)/dist'
    cleanDestinationFolder: true
    overwriteExistingFiles: true

- task: AzureStaticWebApp@0
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/dist'
    app_location: '/'
    skip_app_build: true
    skip_api_build: true
    is_static_export: true
    azure_static_web_apps_api_token: 'b74d57c30f76ac5becbcb50546edea6c8f81400e8e04df7051524f0b3c854ba64-b19ca967-af07-4c65-b285-cdf3ef5a99ed010333666'
